Create Line
LifElect/Some.... pull request #1
Opened 2023-09-20 07:50 UTC by LifElect

2023-09-20 08:57 UTC, Silmarill requested changes
Need corrections.

2023-09-20 08:57 UTC, Silmarill commented on Line
> +{
скобка должна быть на той же строке что и функция

2023-09-20 08:57 UTC, Silmarill commented on Line
> +  Koef = l / g; // Замена повторяющейся операции
Некорректный стиль переменной. Нужно выдерживать камелКейс.

2023-09-20 08:57 UTC, Silmarill commented on Line
> +  double pi2 = pi * 2;
не рекомендуется инициализировать переменные с арифметическим выражением

2023-09-20 08:57 UTC, Silmarill commented on Line
> +  t1 = (pi2) * sqrt(Koef);
зачем скобки вокруг (pi2)

2023-09-20 08:57 UTC, Silmarill commented on Line
> +  t2 = (pi2) * sqrt(Koef * (1 + (0.0625 * pow(sin(a) , 2))));
(pi2) - скобки не нужны
sin - число должно быть в радианах
) , 2 - первый пробел лишний

2023-09-20 08:57 UTC, Silmarill commented on Line
> +  cout.precision(6);
посмотри внимательно как это работает (1 лекция)

2023-09-20 12:00 UTC, LifElect commented on Line
> +  cout.precision(6);
функции с "cout"?

2023-09-27 07:04 UTC, Silmarill requested changes

2023-09-27 07:04 UTC, Silmarill commented on Line
> +  double a = 50, l = 0.994, t1=0, t2=0, t3=0, glKoef=0, pi2 = 0;
сделать блок ввода для а и l

2023-09-27 07:04 UTC, Silmarill commented on Line
> +  double a = 50, l = 0.994, t1=0, t2=0, t3=0, glKoef=0, pi2 = 0;
Если инициализируешь - пробелы слав и справа от =

2023-10-04 07:37 UTC, closed without merging